"use client";

import { useEffect, useMemo, useReducer, useRef } from "react";
import { initQuantumField, initTypewriter, initWaveCanvas } from "./quantumAnimClient";

const CAMS = ["Wide Shot", "Medium Shot", "Close-Up", "POV", "Low Angle", "Aerial"];
const CROPS = [["center", "ЦЕНТР"], ["top", "ВЕРХ"], ["bottom", "НИЗ"], ["close", "КРУПНО"], ["wide", "ШИРЕ"]];
const FORMATS = [
  { id: "shorts", name: "SHORTS · REELS", spec: "9:16 · до 90с", aspect: "9:16", dur: 60 },
  { id: "tiktok", name: "TIKTOK", spec: "9:16 · до 60с", aspect: "9:16", dur: 45 },
  { id: "youtube", name: "YOUTUBE", spec: "16:9 · до 10мин", aspect: "16:9", dur: 300 },
  { id: "custom", name: "СВОЙ ФОРМАТ", spec: "любой ratio", aspect: "1:1", dur: 120 },
];
const STYLES = [
  ["pixar3d", "3D Pixar", "premium 3D family cartoon, soft rounded forms, fluffy materials, expressive eyes"],
  ["cinematic", "Кинематограф", "cinematic animated film look, dramatic key light, high production value"],
  ["ghibli", "Studio Ghibli", "hand-drawn fairytale anime mood, watercolor backgrounds, magical atmosphere"],
  ["watercolor", "Акварель", "soft watercolor cartoon, paper texture, pastel washes"],
  ["comic", "Комикс", "comic book cartoon, bold ink outlines, halftone texture"],
  ["kids", "Детская книжка", "children picture book illustration, cozy soft colors"],
  ["clay", "Пластилин", "claymation cartoon, handmade plasticine texture"],
  ["anime", "Аниме / Манга", "anime manga cartoon, expressive eyes, cel shading"],
];
const DEMO = "Однажды маленький робот проснулся на Луне. Он увидел светящийся след между кратерами. След привёл его к двери, которой вчера не было. За дверью жил потерянный солнечный зайчик. Робот понял, что должен вернуть его на небо. Когда зайчик прыгнул вверх, вся Луна впервые засветилась тёплым светом.";
const init = { step: 1, title: "", format: "shorts", aspect: "9:16", duration: 60, lang: "ru", style: "pixar3d", mood: "light", palette: "AUTO", script: "", heroes: [], scenes: [], selected: 0, crop: "center", busy: false, status: "ГОТОВО ЛОКАЛЬНО" };

function split(text) { return String(text || "").split(/(?<=[.!?…])\s+|\n+/).map(x => x.trim()).filter(x => x.length > 3).slice(0, 24); }
function styleDna(s) { return STYLES.find(x => x[0] === s.style)?.[2] || STYLES[0][2]; }
function cap(s) { s = String(s || "").trim(); return s ? s[0].toUpperCase() + s.slice(1) : s; }
function heroNames(script) { const words = ["робот", "кот", "кошка", "пёс", "собака", "мальчик", "девочка", "зайчик", "заяц", "дракон", "лиса", "волк", "принцесса", "маг", "птица", "монстр"]; const found = words.filter(w => new RegExp(`(^|\\s)${w}[а-яё]*`, "i").test(script)); return [...new Set(found)].slice(0, 3); }
function makeHeroes(s) { const names = heroNames(s.script || DEMO); const base = names.length ? names : ["главный герой"]; return base.map((name, i) => ({ id: `hero_${i + 1}`, name: cap(name), role: i ? "support" : "main", lock: true, dna: `${cap(name)}. Сохранять лицо, силуэт, одежду, материал, цветовое ДНК и узнаваемые детали во всех кадрах. Стиль: ${styleDna(s)}.` })); }
function makeScenes(s, script = s.script || DEMO, heroes = s.heroes.length ? s.heroes : makeHeroes({ ...s, script })) { const lines = split(script); const dur = Math.max(2, Math.round(Number(s.duration || 60) / Math.max(1, lines.length))); return lines.map((line, i) => { const chars = heroes.slice(0, 2).map(h => h.name); const cam = CAMS[i % CAMS.length]; const img = `SCENE PRIMARY FOCUS: ${line}. STYLE DNA: ${styleDna(s)}. Mood: ${s.mood}. Palette: ${s.palette}. Camera: ${cam}. Characters: ${chars.join(", ")}. Preserve Face Lock, outfit lock, color DNA and world continuity. Clean cartoon frame, no text, no watermark.`; return { id: `scene_${String(i + 1).padStart(2, "0")}`, part: Math.floor(i / 4) + 1, order: i + 1, voice: line, camera: cam, duration: dur, image_prompt_en: img, video_prompt_en: `ANIMATE CURRENT FRAME: ${img} Use uploaded frame as source if attached. Smooth expressive cartoon motion for ${dur}s. Preserve exact character identity, face lock, outfit, color DNA, lighting and composition. No subtitles, no UI, no watermark.`, frame: null, frameName: "" }; }); }
function cropText(crop) { return ({ center: "center crop, balanced composition", top: "top weighted crop", bottom: "bottom weighted crop", close: "close-up crop", wide: "wide crop, more environment" })[crop] || "center crop"; }
function payload(s) { return { project: { title: s.title || "Untitled Cartoon", format: s.format, aspect_ratio: s.aspect, duration_sec: s.duration, language: s.lang, pipeline: "cartoon_creator_v4" }, style: { preset: s.style, dna: styleDna(s), mood: s.mood, palette: s.palette }, characters: s.heroes, script: { full_text: s.script, language: s.lang }, storyboard: { part_size: 4, grid: "2x2", scenes: s.scenes.map(sc => ({ ...sc, frame: sc.frame ? "uploaded_frame_attached_in_ui" : null })) } }; }
function reducer(s, a) {
  if (a.type === "reset") return { ...init };
  if (a.type === "clearScript") return { ...s, script: "", heroes: [], scenes: [], selected: 0, status: "СЦЕНАРИЙ ОЧИЩЕН" };
  if (a.type === "set") return { ...s, [a.key]: a.value, scenes: ["style", "mood", "palette", "script"].includes(a.key) ? [] : s.scenes };
  if (a.type === "format") return { ...s, format: a.f.id, aspect: a.f.aspect, duration: a.f.dur, scenes: [] };
  if (a.type === "step") return { ...s, step: Math.max(1, Math.min(6, a.step)), scenes: a.step >= 5 && !s.scenes.length ? makeScenes(s) : s.scenes };
  if (a.type === "scriptAi") return { ...s, script: a.script, heroes: [], scenes: [], busy: false, status: "СЦЕНАРИЙ ГОТОВ" };
  if (a.type === "heroes") return { ...s, heroes: makeHeroes(s), scenes: [], status: "ГЕРОИ И FACE LOCK ГОТОВЫ" };
  if (a.type === "hero") return { ...s, heroes: s.heroes.map((h, i) => i === a.i ? { ...h, [a.key]: a.value } : h), scenes: [] };
  if (a.type === "addHero") return s.heroes.length >= 3 ? s : { ...s, heroes: [...s.heroes, { id: `hero_${s.heroes.length + 1}`, name: `Герой ${s.heroes.length + 1}`, role: "support", lock: true, dna: "описание героя" }], scenes: [] };
  if (a.type === "storyboard") { const heroes = s.heroes.length ? s.heroes : makeHeroes(s); return { ...s, script: s.script || DEMO, heroes, scenes: makeScenes({ ...s, heroes }, s.script || DEMO, heroes), selected: 0, busy: false, status: "STORYBOARD 2×2 ГОТОВ" }; }
  if (a.type === "select") return { ...s, selected: a.i };
  if (a.type === "crop") return { ...s, crop: a.crop, status: `КАДРИРОВКА: ${a.crop}` };
  if (a.type === "frame") return { ...s, scenes: s.scenes.map((sc, i) => i === a.i ? { ...sc, frame: a.frame, frameName: a.name } : sc), selected: a.i, status: "FRAME ЗАГРУЖЕН" };
  if (a.type === "busy") return { ...s, busy: a.value, status: a.status || s.status };
  if (a.type === "status") return { ...s, status: a.status };
  return s;
}

export default function QuantumCartoonCreatorV4() {
  const [s, dispatch] = useReducer(reducer, init);
  const fieldRef = useRef(null), waveRef = useRef(null), tagRef = useRef(null), waveApi = useRef(null);
  const json = useMemo(() => JSON.stringify(payload(s), null, 2), [s]);
  useEffect(() => { document.body.classList.add("route-cartoon"); const stopField = initQuantumField(fieldRef.current); const wave = initWaveCanvas(waveRef.current); const stopType = initTypewriter(tagRef.current); waveApi.current = wave; wave.setDuration(s.duration); return () => { document.body.classList.remove("route-cartoon"); stopField(); wave.destroy(); stopType(); }; }, []);
  useEffect(() => { waveApi.current?.setDuration(s.duration); }, [s.duration]);
  function go(step) { dispatch({ type: "step", step }); try { window.scrollTo({ top: 0, behavior: "smooth" }); } catch {} }
  function next() { if (s.step === 3) { if (!s.heroes.length) dispatch({ type: "heroes" }); return go(4); } if (s.step === 4) { dispatch({ type: "storyboard" }); return go(5); } if (s.step === 5) return go(6); go(s.step + 1); }
  async function generateScript() { dispatch({ type: "busy", value: true, status: "AI ДУМАЕТ · СЦЕНАРИЙ" }); try { const res = await fetch("/api/cartoon/script", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload(s)) }); const data = await res.json(); if (!res.ok || data.ok === false) throw new Error(data.error || "AI error"); dispatch({ type: "scriptAi", script: data.script?.full_text || DEMO }); } catch { dispatch({ type: "scriptAi", script: DEMO }); } }
  function uploadFrame(i, files) { const file = files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = e => dispatch({ type: "frame", i, frame: e.target?.result, name: file.name }); reader.readAsDataURL(file); }
  function copy(text, label = "СКОПИРОВАНО") { navigator.clipboard?.writeText(String(text || "")); dispatch({ type: "status", status: label }); }
  return <div className="qcc-root qcc-v4"><Style /><canvas id="qc" ref={fieldRef} /><div className="hex-grid" /><div className="vignette" /><div className="wrap"><header className="q-header"><div className="q-logo"><div className="q-logo-icon"><div className="orb" /></div><div className="q-logo-text">NEUROCINE</div></div><div className="q-sub">Quantum Cartoon Intelligence · v4</div><div className="q-tagline" ref={tagRef} /></header><div className="q-status-line">◈ {s.status}</div><StepBar step={s.step} go={go} />{s.step===1&&<Step1 s={s} d={dispatch} waveRef={waveRef}/>} {s.step===2&&<Step2 s={s} d={dispatch}/>} {s.step===3&&<Step3 s={s} d={dispatch} generateScript={generateScript}/>} {s.step===4&&<Step4 s={s} d={dispatch} copy={copy}/>} {s.step===5&&<Step5 s={s} d={dispatch} uploadFrame={uploadFrame} copy={copy}/>} {s.step===6&&<Step6 json={json} copy={copy}/>}</div><div className="nav"><button className="nav-back" disabled={s.step===1} onClick={()=>go(s.step-1)}>← НАЗАД</button><button className="nav-next" onClick={next}>{s.step===5?"ЭКСПОРТ →":s.step===6?"ГОТОВО":"ДАЛЕЕ →"}</button></div></div>;
}
function StepBar({step,go}){return <div className="q-stepbar">{[1,2,3,4,5,6].map(i=><div className="qb-node" key={i}><button className={`qb-qubit${i<step?" done":i===step?" active":""}`} onClick={()=>go(i)}><span className="ring"/><span className="sphere">{i<step?"✓":String(i).padStart(2,"0")}</span></button>{i<6&&<div className={`qb-wire${i<step?" done":""}`}/>}</div>)}</div>}
function Head({e,a,b,t}){return <><div className="q-eyebrow">{e}</div><h1 className="q-title"><span className="t-line t-glow">{a}</span><span className="t-line t-dim">{b}</span></h1><p className="q-body">{t}</p></>}
function Field({label,children}){return <div className="q-field"><label className="q-label">{label}</label>{children}</div>}
function Step1({s,d,waveRef}){return <section className="step-panel on"><Head e="Запуск · Шаг 01" a="Настрой" b="проект" t="Формат, длительность и язык мультфильма."/><Field label="Название"><input className="q-inp" value={s.title} placeholder="Например: Кот, который нашёл портал" onChange={e=>d({type:"set",key:"title",value:e.target.value})}/></Field><Field label="Формат"><div className="fmt-grid">{FORMATS.map(f=><button key={f.id} className={`fmt-card${s.format===f.id?" on":""}`} onClick={()=>d({type:"format",f})}><strong className="fmt-name">{f.name}</strong><span className="fmt-spec">{f.spec}</span></button>)}</div></Field><Field label="Длительность"><div className="dur-panel"><div className="dur-display"><div><span className="dur-num">{s.duration}</span><span className="dur-s">с</span></div><div className="dur-sc">≈ {Math.max(1,Math.round(s.duration/7))} сцен</div></div><canvas ref={waveRef} className="wave-canvas"/><input type="range" min="15" max="600" step="5" value={s.duration} onChange={e=>d({type:"set",key:"duration",value:Number(e.target.value)})}/></div></Field></section>}
function Step2({s,d}){return <section className="step-panel on"><Head e="Стиль · Шаг 02" a="Стиль" b="мультфильма" t="Выбери визуальный стиль — он попадёт в prompts."/><Field label="Стиль"><div className="qstyle-rail">{STYLES.map(x=><button key={x[0]} className={`qstyle-card${s.style===x[0]?" on":""}`} onClick={()=>d({type:"set",key:"style",value:x[0]})}><span className="qstyle-preview"><i>✦</i></span><strong>{x[1]}</strong></button>)}</div></Field><Field label="Настроение"><div className="mood-row">{["light","dark","epic","cute","mystery"].map(x=><button key={x} className={`mood-chip${s.mood===x?" on":""}`} onClick={()=>d({type:"set",key:"mood",value:x})}>{x}</button>)}</div></Field></section>}
function Step3({s,d,generateScript}){return <section className="step-panel on"><Head e="Сценарий · Шаг 03" a="Текст" b="диктора" t="Сначала история. После неё AI найдёт героев и подготовит Face Lock."/><button className="mind-btn" disabled={s.busy} onClick={generateScript}>✦ Сгенерировать сценарий</button><div className="qv4-actions"><button onClick={()=>d({type:"clearScript"})}>🧹 Очистить сценарий</button><button className="danger" onClick={()=>d({type:"reset"})}>↺ Сбросить всё</button></div><Field label="Текст сценария"><textarea className="q-inp" rows={9} value={s.script} placeholder="Вставь сценарий или нажми генерацию." onChange={e=>d({type:"set",key:"script",value:e.target.value})}/></Field><div className="meta-strip"><div className="q-meta">СЛОВА: <span>{s.script.trim()?s.script.trim().split(/\s+/).length:0}</span></div><div className="q-meta">СЦЕН: <span>{split(s.script).length}</span></div></div></section>}
function Step4({s,d,copy}){return <section className="step-panel on"><Head e="Герои · Шаг 04" a="Face Lock" b="персонажей" t="Герои создаются после сценария. Проверь или поправь перед storyboard."/><div className="qv2-actions"><button className="qv2-primary" onClick={()=>d({type:"heroes"})}>⚛ Найти героев из сценария</button><button className="add-neural" onClick={()=>d({type:"addHero"})}>⊕ Добавить героя</button></div><div className="neural-list">{s.heroes.map((h,i)=><div className="neural-card on" key={h.id}><div className="nc-head"><div className="nc-orb">{String(i+1).padStart(2,"0")}</div><div className="nc-title"><strong>{h.name}</strong><span>{h.role} · {h.lock?"FACE LOCK":"FREE"}</span></div></div><Field label="Имя"><input className="q-inp" value={h.name} onChange={e=>d({type:"hero",i,key:"name",value:e.target.value})}/></Field><Field label="Visual DNA"><textarea className="q-inp" rows={4} value={h.dna} onChange={e=>d({type:"hero",i,key:"dna",value:e.target.value})}/></Field><button className="qv4-copy" onClick={()=>copy(`CHARACTER REFERENCE SHEET: ${h.name}. ${h.dna}. Full body front view, side view, 3/4 view, expressions. No text, no watermark.`,"REFERENCE PROMPT СКОПИРОВАН")}>COPY REFERENCE PROMPT</button></div>)}</div></section>}
function Step5({s,d,uploadFrame,copy}){const scenes=s.scenes.length?s.scenes:makeScenes(s);const part=Math.floor(s.selected/4);const partScenes=scenes.slice(part*4,part*4+4);const sel=scenes[s.selected]||scenes[0];const img=sel?`${sel.image_prompt_en} FRAMING: ${cropText(s.crop)}. Aspect ${s.aspect}.`:"";const vid=sel?`${sel.video_prompt_en} FRAMING: ${cropText(s.crop)}. Use uploaded frame as source if attached.`:"";return <section className="step-panel on qv4-prod"><Head e="Production · Шаг 05" a="Storyboard" b="2×2 grid" t="Выбери F01–F04, скопируй image prompt, загрузи готовый Frame, выбери кадрировку и получи video prompt."/><button className="qv2-primary" onClick={()=>d({type:"storyboard"})}>↻ Создать / пересобрать storyboard</button><div className="qpart-tabs">{Array.from({length:Math.max(1,Math.ceil(scenes.length/4))}).map((_,i)=><button key={i} className={`qpart-tab${i===part?" on":""}`} onClick={()=>d({type:"select",i:i*4})}>PART {String(i+1).padStart(2,"0")}</button>)}</div><div className="qgrid-2x2">{partScenes.map((sc,local)=>{const gi=part*4+local;return <button key={sc.id} className={`qcell${s.selected===gi?" on":""}`} onClick={()=>d({type:"select",i:gi})}><div className="qcell-media">{sc.frame?<img src={sc.frame} alt="frame"/>:<span className="qframe-pulse"/>}<b>F{String(local+1).padStart(2,"0")}</b></div><strong>{sc.voice}</strong><small>{sc.camera} · {sc.duration}s</small></button>})}</div>{sel&&<div className="qproduction-panel"><div className="qins-head"><strong>{sel.id}</strong><span>{sel.camera} · {sel.duration}s</span></div><Field label="Кадрировка"><div className="mood-row">{CROPS.map(([v,l])=><button key={v} className={`mood-chip${s.crop===v?" on":""}`} onClick={()=>d({type:"crop",crop:v})}>{l}</button>)}</div></Field><div className="qprompt"><div className="qprompt-title"><span>1 · IMAGE PROMPT EN</span><button onClick={()=>copy(img,"IMAGE PROMPT СКОПИРОВАН")}>COPY</button></div><pre>{img}</pre></div><label className="qframe-upload qframe-upload-wide"><input type="file" accept="image/*" onChange={e=>uploadFrame(s.selected,e.target.files)}/><b>2 · Загрузить готовый Frame</b><span>прикрепить картинку к выбранному кадру</span></label><div className="qprompt"><div className="qprompt-title"><span>3 · VIDEO PROMPT EN</span><button onClick={()=>copy(vid,"VIDEO PROMPT СКОПИРОВАН")}>COPY</button></div><pre>{vid}</pre></div></div>}</section>}
function Step6({json,copy}){return <section className="step-panel on"><Head e="Экспорт · Шаг 06" a="JSON" b="pipeline" t="Финальный пакет для генерации."/><button className="qv2-primary" onClick={()=>copy(json,"JSON СКОПИРОВАН")}>💾 Скопировать JSON</button><div className="qprompt"><pre>{json}</pre></div></section>}
function Style(){return <style jsx global>{`.qv4-actions{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}.qv4-actions button,.qv4-copy{min-height:48px;border-radius:16px;border:1px solid rgba(0,212,255,.25);background:rgba(6,10,28,.62);color:#dff8ff;font-weight:900}.qv4-actions .danger{border-color:rgba(255,77,95,.36);color:#ffd7dc}.qgrid-2x2{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:18px 0}.qcell{min-height:270px;border-radius:22px;border:1px solid rgba(0,212,255,.22);background:rgba(4,8,24,.58);color:#fff;text-align:left;padding:12px;overflow:hidden}.qcell.on{border-color:#00d9ff;box-shadow:0 0 24px rgba(0,217,255,.18)}.qcell-media{height:128px;border-radius:16px;background:radial-gradient(circle at 50% 45%,rgba(0,217,255,.22),rgba(3,7,20,.85));display:flex;align-items:center;justify-content:center;position:relative;overflow:hidden;margin-bottom:12px}.qcell-media img{width:100%;height:100%;object-fit:cover}.qcell-media b{position:absolute;top:10px;left:10px;color:#3df3ff}.qcell strong{display:block;font-size:16px;line-height:1.25;margin-bottom:10px}.qcell small{color:#3df3ff}.qproduction-panel{margin-top:18px}.qframe-upload-wide{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:92px;margin:14px 0;border-radius:18px;border:1px dashed rgba(0,212,255,.34);background:rgba(6,10,28,.52);color:#dff8ff}.qframe-upload-wide input{display:none}html[data-theme="light"] .qcell{background:rgba(255,255,255,.86);color:#102a1b;border-color:rgba(22,163,74,.24)}html[data-theme="light"] .qcell small,html[data-theme="light"] .qcell-media b{color:#166534}html[data-theme="light"] .qv4-actions button,html[data-theme="light"] .qv4-copy,html[data-theme="light"] .qframe-upload-wide{background:rgba(255,255,255,.84);color:#14532d;border-color:rgba(22,163,74,.24)}@media(max-width:430px){.qgrid-2x2{gap:10px}.qcell{min-height:238px;border-radius:18px;padding:10px}.qcell-media{height:110px}.qcell strong{font-size:13px}.qv4-actions{gap:10px}.qv4-actions button{font-size:12px}}`}</style>}
