export const TOOL_STATUS = {
  ACTIVE: "active",
};

function pickLang(lang = "ru") {
  return String(lang || "ru").toLowerCase().startsWith("en") ? "en" : "ru";
}

function localizedValue(item = {}, key, lang = "ru") {
  const l = pickLang(lang);
  return item[`${key}_${l}`] || item[key] || "";
}

export const CREATE_TOOLS = [
  {
    id: "studio-home",
    title: "Главная Studio",
    title_ru: "Главная Studio",
    title_en: "Studio Home",
    subtitle: "Внутренняя главная после входа",
    subtitle_ru: "Внутренняя главная после входа",
    subtitle_en: "Internal home after login",
    description: "Пакет доступа, тарифы, статус аккаунта и быстрый старт NeuroCine.",
    description_ru: "Пакет доступа, тарифы, статус аккаунта и быстрый старт NeuroCine.",
    description_en: "Access package, plans, account status and quick start for NeuroCine.",
    icon: "⌂",
    accent: "violet",
    category: "workflow",
    status: TOOL_STATUS.ACTIVE,
    route: "/studio",
    anchor: "studio-home",
    access: ["free", "pro", "owner"],
  },
  {
    id: "create-video",
    title: "Создать ролик",
    title_ru: "Создать ролик",
    title_en: "Create Video",
    subtitle: "Тема → сценарий → storyboard",
    subtitle_ru: "Тема → сценарий → storyboard",
    subtitle_en: "Topic → script → storyboard",
    description: "Быстрый вход в настройку нового проекта: тема, стиль, длительность и запуск сценария.",
    description_ru: "Быстрый вход в настройку нового проекта: тема, стиль, длительность и запуск сценария.",
    description_en: "Fast entry into a new project setup: topic, style, duration and script generation.",
    icon: "+",
    accent: "orange",
    category: "workflow",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#setup",
    anchor: "setup",
    access: ["free", "pro", "owner"],
    primary: true,
  },
  {
    id: "storyboard",
    title: "Storyboard Studio",
    title_ru: "Студия раскадровки",
    title_en: "Storyboard Studio",
    subtitle: "Идея → сценарий → раскадровка → видео",
    subtitle_ru: "Идея → сценарий → раскадровка → видео",
    subtitle_en: "Idea → script → storyboard → video",
    description: "Главный production-пайплайн NeuroCine для сценариев, storyboard JSON, PART-сеток и video prompts.",
    description_ru: "Главный продакшн-пайплайн NeuroCine для сценариев, storyboard JSON, PART-сеток и video prompts.",
    description_en: "The main NeuroCine production pipeline for scripts, storyboard JSON, PART grids and video prompts.",
    icon: "▦",
    accent: "orange",
    category: "workflow",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#storyboard",
    anchor: "storyboard",
    access: ["free", "pro", "owner"],
  },
  {
    id: "script",
    title: "Сценарий",
    title_ru: "Сценарий",
    title_en: "Script",
    subtitle: "Хук, дикторский текст, структура",
    subtitle_ru: "Хук, дикторский текст, структура",
    subtitle_en: "Hook, voiceover text, structure",
    description: "Тема превращается в сценарий для Shorts, Reels или YouTube.",
    description_ru: "Тема превращается в сценарий для Shorts, Reels или YouTube.",
    description_en: "Turns a topic into a script for Shorts, Reels or YouTube.",
    icon: "✍",
    accent: "violet",
    category: "workflow",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#script",
    anchor: "script",
    access: ["free", "pro", "owner"],
  },
  {
    id: "production-pipeline",
    title: "Production Pipeline",
    title_ru: "Продакшн-пайплайн",
    title_en: "Production Pipeline",
    subtitle: "PART grid → кадр → video prompt",
    subtitle_ru: "PART grid → кадр → video prompt",
    subtitle_en: "PART grid → frame → video prompt",
    description: "Рабочая зона Flow/VEO: PART-сетка, выбор кадра, финальный image/video prompt.",
    description_ru: "Рабочая зона Flow/VEO: PART-сетка, выбор кадра, финальный image/video prompt.",
    description_en: "Flow/VEO workspace: PART grid, frame selection and final image/video prompt.",
    icon: "▤",
    accent: "orange",
    category: "workflow",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#production",
    anchor: "production",
    access: ["free", "pro", "owner"],
  },
  {
    id: "studio-package",
    title: "Пакет Studio",
    title_ru: "Пакет Studio",
    title_en: "Studio Package",
    subtitle: "FREE / PRO / DIRECTOR",
    subtitle_ru: "FREE / PRO / DIRECTOR",
    subtitle_en: "FREE / PRO / DIRECTOR",
    description: "Внутренний стартовый блок Studio с тарифами и статусом доступа.",
    description_ru: "Внутренний стартовый блок Studio с тарифами и статусом доступа.",
    description_en: "Internal Studio start panel with plans and access status.",
    icon: "◉",
    accent: "yellow",
    category: "pack",
    status: TOOL_STATUS.ACTIVE,
    route: "/studio#studio-package",
    anchor: "studio-package",
    access: ["free", "pro", "owner"],
  },
  {
    id: "tts-studio",
    title: "TTS Studio",
    title_ru: "Студия озвучки TTS",
    title_en: "TTS Studio",
    subtitle: "Голос диктора и паузы",
    subtitle_ru: "Голос диктора и паузы",
    subtitle_en: "Voiceover, pace and pauses",
    description: "Сценарные настройки озвучки: голос, темп, интонация, паузы и delivery notes.",
    description_ru: "Сценарные настройки озвучки: голос, темп, интонация, паузы и delivery notes.",
    description_en: "Voiceover settings: voice, pace, intonation, pauses and delivery notes.",
    icon: "▥",
    accent: "green",
    category: "pack",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    packTab: "tts",
    access: ["free", "pro", "owner"],
  },
  {
    id: "cover",
    title: "Обложка",
    title_ru: "Обложка",
    title_en: "Cover",
    subtitle: "Thumbnail / poster / preview",
    subtitle_ru: "Thumbnail / постер / preview",
    subtitle_en: "Thumbnail / poster / preview",
    description: "Промпты и варианты для вирусной обложки под YouTube, TikTok и Reels.",
    description_ru: "Промпты и варианты для вирусной обложки под YouTube, TikTok и Reels.",
    description_en: "Prompts and variants for a viral cover for YouTube, TikTok and Reels.",
    icon: "▣",
    accent: "pink",
    category: "pack",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    packTab: "cover",
    access: ["free", "pro", "owner"],
  },
  {
    id: "music-seo",
    title: "Музыка + SEO",
    title_ru: "Музыка + SEO",
    title_en: "Music + SEO",
    subtitle: "Suno, названия, описания",
    subtitle_ru: "Suno, названия, описания",
    subtitle_en: "Suno, titles, descriptions",
    description: "Музыкальный direction, SFX, SEO titles, descriptions и hashtags.",
    description_ru: "Музыкальный direction, SFX, SEO titles, descriptions и hashtags.",
    description_en: "Music direction, SFX, SEO titles, descriptions and hashtags.",
    icon: "↗",
    accent: "cyan",
    category: "pack",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    packTab: "music",
    access: ["free", "pro", "owner"],
  },
  {
    id: "social-pack",
    title: "Social Pack",
    title_ru: "Социальный пакет",
    title_en: "Social Pack",
    subtitle: "YouTube / TikTok / Instagram / Facebook",
    subtitle_ru: "YouTube / TikTok / Instagram / Facebook",
    subtitle_en: "YouTube / TikTok / Instagram / Facebook",
    description: "Публикационный пакет под платформы: captions, hooks, hashtags и descriptions.",
    description_ru: "Публикационный пакет под платформы: captions, hooks, hashtags и descriptions.",
    description_en: "Publishing pack for platforms: captions, hooks, hashtags and descriptions.",
    icon: "⚡",
    accent: "yellow",
    category: "pack",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    packTab: "social",
    access: ["free", "pro", "owner"],
  },
  {
    id: "project-library",
    title: "Проекты",
    title_ru: "Проекты",
    title_en: "Projects",
    subtitle: "Cloud-проекты и snapshots",
    subtitle_ru: "Cloud-проекты и snapshots",
    subtitle_en: "Cloud projects and snapshots",
    description: "Сохранение, поиск, дублирование и загрузка проектов NeuroCine.",
    description_ru: "Сохранение, поиск, дублирование и загрузка проектов NeuroCine.",
    description_en: "Save, search, duplicate and load NeuroCine projects.",
    icon: "☁",
    accent: "blue",
    category: "system",
    status: TOOL_STATUS.ACTIVE,
    route: "/projects",
    anchor: "projects",
    access: ["free", "pro", "owner"],
  },
  {
    id: "series",
    title: "Сериалы",
    title_ru: "Сериалы",
    title_en: "Series",
    subtitle: "Многосерийные проекты",
    subtitle_ru: "Многосерийные проекты",
    subtitle_en: "Multi-episode projects",
    description: "Будущий раздел для серий, сезонов, повторяющихся персонажей и continuity между эпизодами.",
    description_ru: "Будущий раздел для серий, сезонов, повторяющихся персонажей и continuity между эпизодами.",
    description_en: "Future workspace for series, seasons, recurring characters and episode continuity.",
    icon: "▧",
    accent: "purple",
    category: "system",
    status: TOOL_STATUS.ACTIVE,
    route: "/series",
    anchor: "series",
    access: ["free", "pro", "owner"],
  },
  {
    id: "account",
    title: "Профиль",
    title_ru: "Профиль",
    title_en: "Account",
    subtitle: "Аккаунт, тариф, настройки",
    subtitle_ru: "Аккаунт, тариф, настройки",
    subtitle_en: "Account, plan, settings",
    description: "Профиль пользователя, статус доступа, тариф и платежные настройки.",
    description_ru: "Профиль пользователя, статус доступа, тариф и платежные настройки.",
    description_en: "User profile, access status, plan and billing settings.",
    icon: "◌",
    accent: "gray",
    category: "system",
    status: TOOL_STATUS.ACTIVE,
    route: "/account",
    anchor: "account",
    access: ["free", "pro", "owner"],
  },
  {
    id: "director-console",
    title: "Director Console",
    title_ru: "Консоль режиссёра",
    title_en: "Director Console",
    subtitle: "Пульт главного режиссёра",
    subtitle_ru: "Пульт главного режиссёра",
    subtitle_en: "Director control panel",
    description: "Управление доступами, пользователями, ключами и production-состоянием студии.",
    description_ru: "Управление доступами, пользователями, ключами и production-состоянием студии.",
    description_en: "Manage access, users, keys and the studio production state.",
    icon: "⌘",
    accent: "gray",
    category: "system",
    status: TOOL_STATUS.ACTIVE,
    route: "/director/control-room",
    anchor: "director-console",
    access: ["owner"],
  },
];

export const TOOL_GROUPS = [
  { id: "workflow", title: "Рабочий поток", title_ru: "Рабочий поток", title_en: "Workflow" },
  { id: "pack", title: "Production Pack", title_ru: "Продакшн-пак", title_en: "Production Pack" },
  { id: "system", title: "Система", title_ru: "Система", title_en: "System" },
];

export function localizeTool(tool, lang = "ru") {
  if (!tool) return null;
  return {
    ...tool,
    title: localizedValue(tool, "title", lang),
    subtitle: localizedValue(tool, "subtitle", lang),
    description: localizedValue(tool, "description", lang),
  };
}

export function localizeGroup(group, lang = "ru") {
  if (!group) return null;
  return {
    ...group,
    title: localizedValue(group, "title", lang),
  };
}

export function getToolsByGroup(groupId, lang = "ru") {
  return CREATE_TOOLS
    .filter(tool => tool.category === groupId)
    .map(tool => localizeTool(tool, lang));
}

export function getToolGroups(lang = "ru") {
  return TOOL_GROUPS.map(group => localizeGroup(group, lang));
}

export function getCreateTools(lang = "ru") {
  return CREATE_TOOLS.map(tool => localizeTool(tool, lang));
}

export function findTool(id, lang = "ru") {
  return localizeTool(CREATE_TOOLS.find(tool => tool.id === id) || null, lang);
}
