export const TOOL_STATUS = {
  ACTIVE: "active",
};

export const CREATE_TOOLS = [
  {
    id: "storyboard",
    title: "Storyboard Studio",
    subtitle: "Идея → сценарий → раскадровка → видео",
    description: "Главный production-пайплайн NeuroCine для сценариев, storyboard JSON, PART-сеток и video prompts.",
    icon: "▦",
    accent: "orange",
    category: "workflow",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#storyboard",
    anchor: "storyboard",
    access: ["free", "pro", "owner"],
    primary: true,
  },
  {
    id: "series",
    title: "Сериалы",
    subtitle: "Герои → эпизоды → storyboard",
    description: "Отдельная рабочая зона для коротких AI-сериалов: идея, герои, мир, серии и production pipeline.",
    icon: "🎞",
    accent: "red",
    category: "workflow",
    status: TOOL_STATUS.ACTIVE,
    route: "/series",
    anchor: "series",
    access: ["free", "pro", "owner"],
  },
  {
    id: "script",
    title: "Сценарий",
    subtitle: "Хук, дикторский текст, структура",
    description: "Тема превращается в сценарий для Shorts, Reels или YouTube.",
    icon: "✍",
    accent: "violet",
    category: "workflow",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#script",
    anchor: "script",
    access: ["free", "pro", "owner"],
  },
  {
    id: "production-pipeline",
    title: "Production Pipeline",
    subtitle: "PART grid → кадр → video prompt",
    description: "Рабочая зона Flow/VEO: PART-сетка, выбор кадра, финальный image/video prompt.",
    icon: "▤",
    accent: "orange",
    category: "workflow",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#production",
    anchor: "production",
    access: ["free", "pro", "owner"],
  },
  {
    id: "tts-studio",
    title: "TTS Studio",
    subtitle: "Голос диктора и паузы",
    description: "Сценарные настройки озвучки: голос, темп, интонация, паузы и delivery notes.",
    icon: "▥",
    accent: "green",
    category: "pack",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    packTab: "tts",
    access: ["free", "pro", "owner"],
  },
  {
    id: "cover",
    title: "Обложка",
    subtitle: "Thumbnail / poster / preview",
    description: "Промпты и варианты для вирусной обложки под YouTube, TikTok и Reels.",
    icon: "▣",
    accent: "pink",
    category: "pack",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    packTab: "cover",
    access: ["free", "pro", "owner"],
  },
  {
    id: "music-seo",
    title: "Музыка + SEO",
    subtitle: "Suno, названия, описания",
    description: "Музыкальный direction, SFX, SEO titles, descriptions и hashtags.",
    icon: "↗",
    accent: "cyan",
    category: "pack",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    packTab: "music",
    access: ["free", "pro", "owner"],
  },
  {
    id: "social-pack",
    title: "Social Pack",
    subtitle: "YouTube / TikTok / Instagram / Facebook",
    description: "Публикационный пакет под платформы: captions, hooks, hashtags и descriptions.",
    icon: "⚡",
    accent: "yellow",
    category: "pack",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    packTab: "social",
    access: ["free", "pro", "owner"],
  },
  {
    id: "visual-explainer",
    title: "Visual Explainer",
    subtitle: "Разбор кадров и UI-референсов",
    description: "Разбор скриншотов и референсов как продуктовых фич для NeuroCine.",
    icon: "◈",
    accent: "purple",
    category: "system",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#visual-explainer",
    anchor: "visual-explainer",
    access: ["free", "pro", "owner"],
  },
  {
    id: "project-library",
    title: "Project Library",
    subtitle: "Cloud-проекты и snapshots",
    description: "Сохранение, поиск, дублирование и загрузка проектов NeuroCine.",
    icon: "☁",
    accent: "blue",
    category: "system",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#projects",
    anchor: "projects",
    access: ["free", "pro", "owner"],
  },
  {
    id: "director-console",
    title: "Director Console",
    subtitle: "Пульт главного режиссёра",
    description: "Управление доступами, пользователями, ключами и production-состоянием студии.",
    icon: "⌘",
    accent: "gray",
    category: "system",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#director-console",
    anchor: "director-console",
    access: ["owner"],
  },
];

export const TOOL_GROUPS = [
  { id: "workflow", title: "Рабочий поток" },
  { id: "pack", title: "Production Pack" },
  { id: "system", title: "Система" },
];

export function getToolsByGroup(groupId) {
  return CREATE_TOOLS.filter(tool => tool.category === groupId);
}

export function findTool(id) {
  return CREATE_TOOLS.find(tool => tool.id === id) || null;
}
