export const TOOL_STATUS = {
  ACTIVE: "active",
  READY_UI: "ready_ui",
  PLANNED: "planned",
};

export const CREATE_TOOLS = [
  {
    id: "storyboard",
    title: "Storyboard Studio",
    subtitle: "Идея → сценарий → раскадровка → видео",
    description: "Главный production-пайплайн NeuroCine для сценариев, storyboard JSON, PART-сеток и video prompts.",
    icon: "▦",
    accent: "orange",
    category: "main",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#storyboard",
    anchor: "storyboard",
    access: ["free", "pro", "owner"],
    primary: true,
  },

  {
    id: "quick-storygrid",
    title: "Quick Storygrid",
    subtitle: "Идея → сцены → prompts",
    description: "Быстрая форма: идея, длина, формат, сцены, стиль и запуск storyboard без поиска по большой Studio.",
    icon: "▤",
    accent: "orange",
    category: "main",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#quick-tools",
    anchor: "quick-tools",
    access: ["free", "pro", "owner"],
  },
  {
    id: "script",
    title: "Сценарий",
    subtitle: "Хук, дикторский текст, структура",
    description: "Быстрый старт: тема превращается в сценарий для Shorts, Reels или YouTube.",
    icon: "✍",
    accent: "violet",
    category: "main",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#script",
    anchor: "script",
    access: ["free", "pro", "owner"],
  },
  {
    id: "viral-shorts",
    title: "Виральные Shorts",
    subtitle: "Автогенерация идей и production pack",
    description: "Шаблоны под TikTok, Shorts и Reels: сценарий, обложка, TTS, SEO и hashtags.",
    icon: "⚡",
    accent: "yellow",
    category: "main",
    status: TOOL_STATUS.READY_UI,
    route: "/storyboard#quick-tools",
    anchor: "quick-tools",
    access: ["free", "pro", "owner"],
  },
  {
    id: "cover",
    title: "Обложка",
    subtitle: "Thumbnail / poster / preview",
    description: "Промпты и варианты для вирусной обложки под YouTube, TikTok и Reels.",
    icon: "▣",
    accent: "pink",
    category: "image",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    access: ["free", "pro", "owner"],
  },
  {
    id: "text-to-image",
    title: "Создать фото",
    subtitle: "Из текста в визуал",
    description: "Будущий модуль Text-to-Image: кадры, постеры, персонажи и стили.",
    icon: "▧",
    accent: "blue",
    category: "image",
    status: TOOL_STATUS.READY_UI,
    route: "/storyboard#production",
    anchor: "production",
    access: ["pro", "owner"],
  },
  {
    id: "smart-edit",
    title: "Умная правка",
    subtitle: "Из фото в фото",
    description: "Будущий AI edit: заменить фон, стиль, объект или улучшить кадр.",
    icon: "◈",
    accent: "purple",
    category: "image",
    status: TOOL_STATUS.PLANNED,
    route: "/storyboard#production",
    anchor: "production",
    access: ["pro", "owner"],
  },
  {
    id: "text-to-video",
    title: "Создать видео",
    subtitle: "Veo / Kling / Runway-ready",
    description: "Будущий Video Generation hub поверх video provider adapters.",
    icon: "▻",
    accent: "red",
    category: "video",
    status: TOOL_STATUS.READY_UI,
    route: "/storyboard#production",
    anchor: "production",
    access: ["pro", "owner"],
  },
  {
    id: "motion-control",
    title: "Motion Control",
    subtitle: "Движение и камера",
    description: "Видео-референс движения + изображение персонажа → управляемая анимация.",
    icon: "⌁",
    accent: "green",
    category: "video",
    status: TOOL_STATUS.PLANNED,
    route: "/storyboard#production",
    anchor: "production",
    access: ["pro", "owner"],
  },
  {
    id: "avatar",
    title: "AI-аватар",
    subtitle: "Аватары и lip sync",
    description: "Будущий talking-avatar модуль: фото + текст/голос → говорящий персонаж.",
    icon: "◉",
    accent: "gray",
    category: "video",
    status: TOOL_STATUS.PLANNED,
    route: "/storyboard#production",
    anchor: "production",
    access: ["pro", "owner"],
  },
  {
    id: "lip-sync",
    title: "Lip Sync",
    subtitle: "Синхронизация губ",
    description: "Будущий модуль для говорящих голов, дубляжа и аватаров.",
    icon: "☊",
    accent: "teal",
    category: "audio",
    status: TOOL_STATUS.PLANNED,
    route: "/storyboard#production",
    anchor: "production",
    access: ["pro", "owner"],
  },
  {
    id: "audio",
    title: "Голос и аудио",
    subtitle: "TTS, музыка, SFX",
    description: "TTS-настройки, Suno/music prompts, SFX и audio mix notes.",
    icon: "▥",
    accent: "green",
    category: "audio",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    access: ["free", "pro", "owner"],
  },
  {
    id: "seo-social",
    title: "SEO / Social Pack",
    subtitle: "Названия, описания, hashtags",
    description: "Публикационный пакет под YouTube, TikTok, Instagram и Facebook.",
    icon: "↗",
    accent: "cyan",
    category: "publish",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#pack",
    anchor: "pack",
    access: ["free", "pro", "owner"],
  },
  {
    id: "project-library",
    title: "Project Library",
    subtitle: "Cloud-проекты и snapshots",
    description: "Сохранение, поиск, дублирование и загрузка проектов NeuroCine.",
    icon: "☁",
    accent: "blue",
    category: "library",
    status: TOOL_STATUS.ACTIVE,
    route: "/storyboard#projects",
    anchor: "projects",
    access: ["free", "pro", "owner"],
  },
  {
    id: "all-tools",
    title: "Все инструменты",
    subtitle: "Карта возможностей NeuroCine",
    description: "Единый каталог модулей: active, UI-ready и planned features.",
    icon: "…",
    accent: "gray",
    category: "library",
    status: TOOL_STATUS.READY_UI,
    route: "/storyboard#tools",
    anchor: "tools",
    access: ["free", "pro", "owner"],
  },
];

export const TOOL_GROUPS = [
  { id: "main", title: "Главное" },
  { id: "image", title: "Изображение" },
  { id: "video", title: "Видео" },
  { id: "audio", title: "Голос и аудио" },
  { id: "publish", title: "Публикация" },
  { id: "library", title: "Библиотека" },
];

export function getToolsByGroup(groupId) {
  return CREATE_TOOLS.filter(tool => tool.category === groupId);
}

export function findTool(id) {
  return CREATE_TOOLS.find(tool => tool.id === id) || null;
}
